### ISSUE TITLE
Logistics Checklist for Sessions 3 and 4

### ISSUE THREAD

**Issue by kkale25** [ICPI/Data-Core-Competencies-using-R#31]
- [ ] Room reservation: October 18 from 9AM - 5:30PM, October 19 from 9AM-1PM
Ideally Shared Conf A&B
- [ ] Power strips
- [ ]  wifi/hotspots (Kashmira has 2, DUAT has a few)
- [ ]  adobe connect set up (Rebecca)
- [ ]  open phone line (Rebecca)
- [ ]  room set up: classroom style
- [ ] breakfast for participants on Day 1
