### ISSUE TITLE
Logistics Checklist

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#4]
- [ ]   Power strips
- [ ]   wifi/hotspots
- [ ]   adobe connect set up + recording
- [ ]   open phone line
- [ ] room set up: classroom style
![image](https://user-images.githubusercontent.com/5234106/41609160-22c838d0-73b8-11e8-8e27-008922d5e67b.png)
- [ ]   Monitor Slack channel (R users group slack channel)
- [ ]   Hand-outs
- [ ]   Flash drive for transferring files as a backup

Checklist from the Tableau training. Please add anything else you may need.

**Comment by shapaklyak** [comment]
see issue 23 from Tableau Training: https://github.com/ICPI/tableau_training/issues/23
