### ISSUE TITLE
Communications Checklist

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#9]
These are the emails that need to be drafted and sent to potential participants and registered participants

To Do
--
- [x] ICPI Event form(s) for training, office hours, etc. @shazadahmed10 
- [x] "save the date" @hessionra 
- [x] Registration & pre-training assessment  @jb3436 drafted email @hessionra to send email _(August 2)_
- [x] Send registration closing email and reminder
- [x] Compile registered participants from [GForms ](https://docs.google.com/forms/d/e/1FAIpQLScbu7PTSKXmP7b5eQ8XkBIbO4kETzk0K6qxj7rj2Lza6ZEcCg/viewform?usp=sf_link) and  send to R training team @kkale25 _(August 14)_
- [x] (email 2) Send  welcome email to registered participants (@kkale25 to draft @hessionra to send) _(August 13)_
- [x] (email 2) Pre-work for registered participants @shazadahmed10 to draft @hessionra to send _(send on Aug.13)_
- [x] Agenda (@achafetz @shazadahmed10 to draft @hessionra to send) _(INSERT DATE)_
- [x] (email 2) Office hours? _(@kkale25 to draft email, ICPI to email out - Aug.20 and Aug.21)_

others? @jb3436 @kkale25 @jaliasd @achafetz @HoustonJamie @imujawar @shazadahmed10

**Comment by shazadahmed10** [comment]
Event form for all 4 session completed.

**Comment by jb3436** [comment]
@shazadahmed10 we can use the registration email as a "save the date".

**Comment by kkale25** [comment]
@shazadahmed10, can you add the language for the pre-work email in a comment on this issue? I will incorporate it into the language I have for the "Welcome" email and we'll send both the pre-work and the welcome email as one. 

For the office hours, I was thinking we could send calendar invites to the registered participants so they have it on their calendar and remember. That can be sent out on Aug 13th as well after registration closes.

**Comment by kkale25** [comment]
@hessionra 
We plan to have office hours for the R training. Could you please create two event invites for the below office hours times and send to the folks who have registered for the training? We should send this out on Monday 8/13 (after the registration deadline).  In the invite, please be sure to uncheck the “Request Responses” options. We don't need a response - rather just putting this on their calendar for reference. 

I've already reserved NA for these times but could you add a Skype link into the invite?  


BODY OF THE INVITE:

Dear ICPI and SI Communities, 
Feel free to share this with your colleagues who may benefit from this course

To ensure participants are fully prepared and supported for the upcoming ICPI R training, we plan to host “ICPI R Training Office Hours”. Office hours will be held on Monday, August 20th from 2-3PM EST and Tuesday, August 21st from 11AM-12PM EST. They will be held in the North America conference room. If you’d like to call in, we’ll be available on the below Skype link. 

You’re welcome to bring any questions, issues, concerns, etc. related to downloading R and RStudio, the videos, the pre-work, or the upcoming sessions. We’re here to help you be best prepared for the training! 

Thank you,
ICPI

**Comment by shapaklyak** [comment]
@kkale25 this looks good - just wondering why we are using Skype instead of Adobe Connect for office hours? Some folks don't have access to Skype.

**Comment by kkale25** [comment]
@shapaklyak @hessionra Sorry! I always forget Skype isn't accessible to all. Rebecca, would you mind adding an Adobe connect session with a phone line?

Thanks!
K

**Comment by kkale25** [comment]
@hessionra Here's the "Welcome/Pre-work" email we should also send out on Monday (along with the calendar invites for office hours)

Subject line: ICPI R Training - Welcome and Pre-Training Exercise

Dear R Training participants,

Welcome to the ICPI R Training series! We're excited you are able to participate in this course and we look forward to helping you build your skills in R. This four-part training course is intended for people at the beginner to medium-level experience with R. The course will expose to you a variety of R competencies and skills over four sessions. Further details on the course objectives, agenda, etc. to come soon! 

As you saw in the registration email, please make sure you have the most recent versions of both R AND RStudio installed.
•	Download R: here
•	Download RStudio: here

In preparation for this training, we recommend viewing the following videos:
•	Intro video on Using RStudio
•	How to download R & RStudio
•	Coding Basics

Have you already watched the videos....but are still feeling a bit intimidated? Do you wish you were more prepared? Are you seeking out a more hands-on way to engage with R before the training?  

If you answered yes to any of the questions above, try out R on your own through this easy, step-by-step pre-training exercise to help become familiarized with:
• The RStudio interface
• Interacting with datasets in RStudio
• R packages

This is a self-paced exercise that should take 20-30 minutes to complete. If you have any questions on the pre-work exercise, please come to the R training office hours with your questions! Office hours are on Monday, August 20th from 2-3PM EST and Tuesday, August 21st from 11AM-12PM EST in the North America conference room or via Adobe Connect/conference line.

Good luck and we're looking forward to seeing you at the training!

**Comment by shapaklyak** [comment]
@kkale25 thanks! Skype hasn't been working for me lately, either. **Referencing #14 **w**hen it's finalized** to be attached to this email

**Comment by kkale25** [comment]
@hessionra is ready to send pre-work email and office hours calendar invite but having some IT issues. Should be sent soon.

**Comment by hessionra** [comment]
Sent out 8/14!

**Comment by kkale25** [comment]
Summary of registered participants and responses attached here. Please review!

@shazadahmed10 Do you think we need to have another meeting before Session 1/2 on 8/23? 

[R Training_Registration Summary.pptx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2288234/R.Training_Registration.Summary.pptx)

**Comment by kkale25** [comment]
Looks like all the communication has been sent out. Anything missing?

**Comment by shazadahmed10** [comment]
Links to training materials need to be circulated.
